apiVersion: apps/v1
kind: Deployment

metadata:
  name: development-operations-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: development-operations-api

  template:
    metadata:
      labels:
        app: development-operations-api

    spec:
      containers:
      - name: main
        image: ghcr.io/etauker-projects/development-operations-api-main:main
        imagePullPolicy: Always
        ports:
        - containerPort: 9999
        env:
        - name: DATABASE_HOST
          value: "postgres"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_SSL_CONNECTION
          value: "false"
        - name: DATABASE_MAX_POOL_SIZE
          value: "1"
        - name: DATABASE_IDLE_TIMEOUT_MILLIS
          value: "1000"
        - name: DATABASE_CONNECTION_TIMEOUT_MILLIS
          value: "1000"
        - name: LOGGER_LOG_LEVEL
          value: "ALL"

      imagePullSecrets:
      - name: github-registry
