version: '3'

services:
  reverse-proxy:
    container_name: traefik
    image: traefik:v2.10
    restart: unless-stopped
    # network_mode: host
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--entrypoints.web.address=:80"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8010:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - traefik

  # whoami:
  #   image: "traefik/whoami"
  #   container_name: whoami
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`dev.etauker.ie`) && PathPrefix(`/test/`)"
  #     - "traefik.http.routers.whoami.entrypoints=web"
  #     - "traefik.http.middlewares.strip-test-prefix.stripprefix.prefixes=/test"
  #     - "traefik.http.routers.whoami.middlewares=strip-test-prefix@docker"
  #     - "traefik.http.services.whoami.loadbalancer.server.port=80"
  #   # networks: 
  #   #   - traefik_default

networks:
  traefik:
    name: traefik
